### PR TITLE
Fix "--only : Missing argument of type keep" #14

### PR DESCRIPTION
**Pull request by michal-turzynski**
More details here: https://github.com/adamzapasnik/vscode-elixir-test-explorer/issues/14

### CODE REVIEW

**Comment by adamzapasnik** [comment]
I'll test it tomorrow. But I think it'd be best to use a character that couldn't be present in a method's name like`*` or `-` instead of `___`.

But on the other hand I don't know if `*` or `-` would work?

**Comment by michal-turzynski** [comment]
> I'll test it tomorrow. But I think it'd be best to use a character that couldn't be present in a method's name like`*` or `-` instead of `___`.
> 
> But on the other hand I don't know if `*` or `-` would work?

That makes sense! Also, `*` worked as expected for me - meaning it returned all the test cases without executing them 
cc @adamzapasnik

**Comment by adamzapasnik** [comment]
could you amend the changes to use `*` @michal-turzynski 

(btw. thank you very much for the contribution, last week I was busy and didn't have time to handle it)

**Comment by michal-turzynski** [comment]
Pleasure! Thank you @adamzapasnik for building the extension 🙏

Just pushed the commit as you suggested: `--only="___"` changed to `--only="*" `

**Pull request merged**
